# Generated by Django 3.2.6 on 2021-08-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_complete_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='No Description', max_length=250, null=True),
        ),
    ]
